= Plugins under Development

== Important: Beta Plugins!!!

=== Use at your own risk

These plugins are in development and not yet considered stable enough to
be published on the main OpenCPN website. They may cause your computer
to freeze or result in OpenCPN failing to work correctly. They are used
entirely at your own risk.

=== Hosted Plugins

Plugin authors who wish to have a link to their new plugin hosted here
should contact one of the following by PM (Private Message): Rick
Gleason (rgleason)
http://www.cruisersforum.com/forums/private.php?do=newpm&u=100424.html[PM
Rick], Mike Rossiter (Rasbats)e
http://www.cruisersforum.com/forums/private.php?do=newpm&u=105199[PM
Mike], preferably, from the
http://www.cruisersforum.com/forums/f134/[Cruisers Forum]. They will
create an entry in FIXME

=== Testing

Open the individual plugin page for links to the Git Source code and
Compiled versions found under Git Releases (Usually Windows). For Linux
and other operating systems you may need to compile your own version.
Additional information will be available such as OpenCPN version
compatibility and comments from the Cruisers Forum.

=== Use of Nmea data stream for Testing

You can download NMEA files relevant to testing the plugins with VDR
Player here. Check to see if your plugin Developer has provided somee or
find one that has the necessary data stream.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn&do=media&ns=opencpn:files:nmea[Download
NMEA Beta Plugin Test Files]

=== Move to Production Release

xref:plugin_submissions.adoc[] explains
what happens when plugin authors are ready to move their plugin to a
production release that can be hosted on the Downloads page of the main
OpenCPN website.
