= Building and installing on Cubieboard 2 with HW acceleration

Start with a fresh install of the desktop version of cubian on an SD
card, from here:

http://cubian.org/downloads/

– The stock cubian image has a small amount of free space on the root
filesystem. You need to follow the instructions here to expand (I just
told it to use the entire amount of my 16GB card):

http://cubian.org/2013/08/12/enlarge-cubian-rootfs-partition/

– Install some additional packages:

....
$ sudo apt-get install mesa-utils build-essential git cmake libx11-dev
....

– Download the forked version of the glshim:

....
$ git clone https://github.com/seandepagnier/glshim.git
....

– Build glshim library and copy the results to a suitable location:

....
$ cd ../../glshim
$ cmake .
$ make GL
$ sudo cp glshim/lib/libGL.so.1 /usr/local/lib/
$ sudo cp -r glshim/include/GLES/ /usr/local/include/
....

– Build and install glues from source:

....
$ git clone https://github.com/ssvb/glues.git
$ cd glues
$ cmake .
$ make
$ sudo cp libGLU.so.1 /usr/local/lib
....

– Build OpenCPN - Follow the standard Linux build instructions for
Ubuntu/Debian

– Within OpenCPN, enable opengl, texture compression and the texture
compression cache. Then rebuild the chart database (took a long time on
my cubieboard2).
