= Legacy Plugins

The term _Legacy Plugins_ refers to plugins installed without involving the
Plugin Manager or any other part of the OpenCPN core. This was the only
way to deploy plugins before the new Plugin Manager in 5.2.2.

Packages are deployed as NSIS installers in Windows, .img packages on
MacOS and Debian .deb packages on Debian/Ubuntu. There are no flatpak
legacy plugins. Users install these packages in the same way as OpenCPN
and other programs are installed.

For visibility, plugin packages are published at
https://opencpn.org/OpenCPN/info/downloadplugins.html[].

Should there be a need to publish new legacy packages, Pavel (@nohal)
or Dave (@bdbcat) should be contacted so the information at
opencpn.org can be updated. The xref:plugin_guidelines.adoc[rules]
described for modern plugins applies also for legacy ones.

Both the xref:managed-plugins:ROOT:index.adoc[Shipdriver] and the
xref:pm-tp-template.adoc[Testplugin] templates supports creation of
legacy packages.

Legacy plugins are installed in system directories which typically are
read-only for regular users. For this reason, installation requires
root or administrator privileges.

The Plugin Manager installs plugins in directories which could be modified
by a regular users. Legacy plugins are listed, but cannot be modified.
