= About This Manual

The purpose of this manual is provide necessary info about OpenCPN
development for new and old contributors. It's currently a work in
progress and should not be used to obtain information. The currently
used manual is available at
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual[The OpenCPN website]

The manual is written for readers with basic programming skills.

== Contents

The first section, OpenCPN Development, contains info on how to build
the main program and how to contribute to the OpenCPN project.

The second section, Plugin Development, covers development and
maintenance of plugins. This includes programming info like API and
other interfaces, build setup and plugin deployment.

The Resources section contains various useful resources, notably
on-line NMEA tools.

The Manual Maintenance section does indeed cover how to contribute
to this manual

The Attic contains old, basically outdated docs which still could have
some value in specific situations.

== Context
This is  one of four manuals available:

* https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual[User's Manual]
* http://nowhere.net[Advanced User's Manual]
* https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html[User Plugin Manual]
* https://leamas.github.io/ocpn-manuals/ocpn-dev-manual/5.3.1/AboutThisManual.html[Development manual - Leamas]
*

IMPORTANT: FIXME manual links
