= NSIS Installation Directory

The NSIS file *opencpn_[version]_setup.exe* created by "cpack" which
contains all the files in the listing below (compressed). This *.exe
file is found in: EXAMPLES:

....
    ..\Github\OpenCPN\build\_CPack_Packages\win32\NSIS\opencpn_4.5.221_setup.exe
    ..\GitHub\vdr_pi\build\_CPack_Packages\win32\NSIS     
    ..\GitHub\vdr_pi\build\_CPack_Packages\win32\     
....

when the user executes the file, Opencpn is installed into Windows which
works without any need for additional files or directories. The four
internal plugins (release versions) are included. This is the most
convenient way to install Windows OpenCPN.

NSIS installation directory used to create the package.

....
..\Github\Ocpn\build\_CPack_Packages\win32\NSIS\opencpn_4.5.221_setup
....

OR

....
 source\build\_CPack_Packages\win32\NSIS\opencpn_4.5.221_setup
....

....
NSIS installation directory used to create the package.

8 Subdirectories
-----------------
doc
gshhs
plugins (4 internal *_pi.dll and 4 directories)
s57data
share  (where is docs & locales found? FIXME)
sounds
tcdata
uidata  (created from various directories)

Crash Reporting Files
--------------------
CrashRpt1403.dll
crashrpt_lang.ini
CrashSender1403.exe
dbghelp.dll

11 DLL Files
(copied from buildwin -vr, gtk,expat, etc directories)
------------------
cairo.dll
expat.dll
fontconfig.dll
iconv.dll
libcurl.dll
libpng16.dll
libxml2.dll
msvcp120.dll
msvcr120.dll
pixman-1.dll
zlib1.dll

16 wxWidgets files
----------------------
wxbase30u_net_vc_custom.dll
wxbase30u_vc_custom.dll
wxbase30u_xml_vc_custom.dll
wxmsw30u_adv_vc_custom.dll
wxmsw30u_aui_vc_custom.dll
wxmsw30u_core_vc_custom.dll
wxmsw30u_gl_vc_custom.dll
wxmsw30u_html_vc_custom.dll
wxmsw30u_media_vc_custom.dll
wxmsw30u_propgrid_vc_custom.dll
wxmsw30u_qa_vc_custom.dll
wxmsw30u_ribbon_vc_custom.dll
wxmsw30u_richtext_vc_custom.dll
wxmsw30u_stc_vc_custom.dll
wxmsw30u_webview_vc_custom.dll
wxmsw30u_xrc_vc_custom.dll

4 Other files
------------------
ocpn_gltest1.exe
opencpn.exe
license.txt
PrivacyPolicy.txt

Uidata Folder List
--------------------
See ..\_CPack_Packages\win32\NSIS\opencpn_4.5.221_setup\uidata

3 SVG Directories  (from ..\data\svg)
---------------------
  journeyman  (8 svg files)
  journeyman_flat (8 svg files)
  traditional (75 svg files)

4 Toolbar Files  (from ..\src\bitmaps)
---------------------
styles.xml
toolicons_journeyman.png
toolicons_journeyman_flat.png
toolicons_traditional.png
and any files in the ..\styles folder

5 Icon Files  (from ..\src\bitmaps)
-----------------
iconAll.png
iconMinimum.png
iconRMinus.png
iconRPlus.png
iconStandard.png
....
