= FAQ

How can errors in the manual be reported?;;
For issues in the overall manual, please use
https://github.com/opencpn-manuals/plugins/issues.
+
For minor edit  for specific plugins, please use the _Edit This Page_
link which is available top-right in every manual page. This leads
to a GUI dialog where it is possible to propose changes directly.
+
For other problems with specific plugins, please file the issue
against the plugin. The github repository link is usually on top
of the manual page.

How could images be displayed in Firefox using the asciidoc plugin?;;

At the top of the document (.adoc) add the attribute ``:imagesdir:
../images/'' This will not appear in the page but controls the location
of the images.

Where is the latest build of the OpenCPN Plugins Manual?;;

Latest build is at https://opencpn-manuals.github.io/plugins.

How can the manual be edited?;;
. Top right of your pages you will see `Edit this page'. Using this
allows edits of the manual on Github. On the next build of your plugin
the edits will be seen in the manual (after the main manual is updated).
. Using the manual pages in your plugin repository.


Are there tools that converts markdown  to asciidoc?;;

Are there tools that ``automagically'' converts markdown
e.g.,  the README.md file in the github repo) to asciidocs? Yes
https://pandoc.org/[pandoc] does this. It's not perfect, but usable.

BTW if you need HTML for a help button you will create it by using a local build of the manual.
The HTML could be placed in a folder in your plugin data directory and referenced
by the plugin.


