#!/bin/sh
#
# Rebuild all manuals found in sources, primarely to hunt for errors.

top=$(git rev-parse --show-toplevel)
for dir in $top/sources/*; do
    if [ -f $dir/manual/site.yml ]; then
        cd $dir/manual
        echo "==== Building ${dir/$top/plugins}/manual/site.yml"
        antora site.yml
    else
        echo "No manual/site.yml found in ${dir/$top/plugins}" >&2
    fi
done
