INFO linkcheck.cmdline 2021-08-14 14:06:04,263 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.0.1
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it under
certain conditions. Look at the file `LICENSE' within this distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2021-08-14 14:06:04+000

URL        `https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual'
Name       `User Manual'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-plugins/0.1/index.html, line 38, col 15
Real URL   https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
Info       The URL is outside of the domain filter, checked only
           syntax.
Warning    [url-whitespace] Leading or trailing whitespace in URL
           `https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
           '.
Result     Valid: filtered
10 threads active,   114 links queued,   48 links in 172 URLs checked, runtime 1 seconds
 9 threads active,   729 links queued,  519 links in 1257 URLs checked, runtime 6 seconds

URL        `../install_and_enable.html'
Name       `Plugins - Install and Enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/ais_radar_display/0.1/ais_radar_display.html, line 609, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/ais_radar_display/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/ais_radar_display/install_and_enable.html'>

URL        `_images/ocpn-optionsmenu.jpeg'
Name       `ocpn optionsmenu'
Parent URL file:///home/runner/work/plugins/plugins/docs/bsb4_charts/0.1/bsb4_charts.html, line 637, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/bsb4_charts/0.1/_images/ocpn-optionsmenu.jpeg
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/bsb4_charts/0.1/_images/ocpn-optionsmenu.jpeg'>

URL        `photolayer#geotiff_sources'
Name       `this section'
Parent URL file:///home/runner/work/plugins/plugins/docs/photolayer/0.1/photolayer.html, line 618, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/photolayer/0.1/photolayer
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/photolayer/0.1/photolayer'>

URL        `_images/chartscale_.png.detail.html'
Name       `chartscale .png.detail'
Parent URL file:///home/runner/work/plugins/plugins/docs/chartscale/0.1/chartscale.html, line 530, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/chartscale/0.1/_images/chartscale_.png.detail.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/chartscale/0.1/_images/chartscale_.png.detail.html'>

URL        `../install_and_enable.html'
Name       `Plugins -\nInstall and Enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/objsearch/0.1/objsearch.html, line 641, col 25
Real URL   file:///home/runner/work/plugins/plugins/docs/objsearch/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/objsearch/install_and_enable.html'>

URL        `_images/watchdog/watchdog_19056_001_ocpn_downloads.jpeg'
Name       `watchdog 19056 001 ocpn downloads'
Parent URL file:///home/runner/work/plugins/plugins/docs/objsearch/0.1/objsearch.html, line 651, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/objsearch/0.1/_images/watchdog/watchdog_19056_001_ocpn_downloads.jpeg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/objsearch/0.1/_images/watchdog/watchdog_19056_001_ocpn_downloads.jpeg'>

URL        `../../manual/plugins/chartscale/chartscale_enable.png'
Name       `image'
Parent URL file:///home/runner/work/plugins/plugins/docs/chartscale/0.1/chartscale.html, line 636, col 51
Real URL   file:///home/runner/work/plugins/plugins/docs/manual/plugins/chartscale/chartscale_enable.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/manual/plugins/chartscale/chartscale_enable.png'>

URL        `../install_and_enable.html'
Name       `install_and_enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/logbook/0.1/logbook.html, line 569, col 8
Real URL   file:///home/runner/work/plugins/plugins/docs/logbook/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/logbook/install_and_enable.html'>

URL        `_images/nmeacon.jpg'
Name       `nmeacon'
Parent URL file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/nmea_converter.html, line 557, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/_images/nmeacon.jpg
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/nmea_converter/0.1/_images/nmeacon.jpg'>

URL        `../install_and_enable.html'
Name       `Install and Enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/find-it/0.1/find-it.html, line 565, col 8
Real URL   file:///home/runner/work/plugins/plugins/docs/find-it/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/find-it/install_and_enable.html'>

URL        `../../advanced_features/nmea_sentences.html'
Name       `NMEA\nSentences Page'
Parent URL file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/nmea_converter.html, line 630, col 16
Real URL   file:///home/runner/work/plugins/plugins/docs/advanced_features/nmea_sentences.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/advanced_features/nmea_sentences.html'>

URL        `../../options_setting/connections.html'
Name       `OpenCPN Connections Tab'
Parent URL file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/nmea_converter.html, line 730, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/options_setting/connections.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/options_setting/connections.html'>

URL        `../install_and_enable.html'
Name       `Plugin Installation Instructions'
Parent URL file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/nmea_converter.html, line 817, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/nmea_converter/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/nmea_converter/install_and_enable.html'>

URL        `../../manual/route_plugin.png'
Name       `image'
Parent URL file:///home/runner/work/plugins/plugins/docs/route_great_circle/0.1/route_great_circle.html, line 557, col 24
Real URL   file:///home/runner/work/plugins/plugins/docs/manual/route_plugin.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/manual/route_plugin.png'>

URL        `../../manual/gc-comp.png'
Name       `image'
Parent URL file:///home/runner/work/plugins/plugins/docs/route_great_circle/0.1/route_great_circle.html, line 566, col 24
Real URL   file:///home/runner/work/plugins/plugins/docs/manual/gc-comp.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/manual/gc-comp.png'>

URL        `_images/nemaconverter-normalize-degrees-crop.png.detail.html'
Name       `nemaconverter normalize degrees crop.png.detail'
Parent URL file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/nmea_converter.html, line 1339, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/nmea_converter/0.1/_images/nemaconverter-normalize-degrees-crop.png.detail.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/nmea_converter/0.1/_images/nemaconverter-normalize-degrees-crop.png.detail.html'>

URL        `../plugin_messaging.html'
Name       `plugin_messaging'
Parent URL file:///home/runner/work/plugins/plugins/docs/odraw/0.1/odraw.html, line 685, col 8
Real URL   file:///home/runner/work/plugins/plugins/docs/odraw/plugin_messaging.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/odraw/plugin_messaging.html'>

URL        `_images/od-wx-rte-boundary-guard-zone-grib-clim.jpg'
Name       `od wx rte boundary guard zone grib clim'
Parent URL file:///home/runner/work/plugins/plugins/docs/odraw/0.1/odraw.html, line 723, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/odraw/0.1/_images/od-wx-rte-boundary-guard-zone-grib-clim.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/odraw/0.1/_images/od-wx-rte-boundary-guard-zone-grib-clim.jpg'>

URL        `_images/cn-03-time.jpg'
Name       `cn 03 time'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1873, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-03-time.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-03-time.jpg'>

URL        `_images/cn-04-drshift.jpg'
Name       `cn 04 drshift'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1882, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-04-drshift.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-04-drshift.jpg'>

URL        `_images/cn-05-config.jpg'
Name       `cn 05 config'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1890, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-05-config.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-05-config.jpg'>

URL        `_images/cn-06-parameters.jpg'
Name       `cn 06 parameters'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1898, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-06-parameters.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-06-parameters.jpg'>

URL        `_images/cn-07-sight-sun.jpg'
Name       `cn 07 sight sun'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1907, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-07-sight-sun.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-07-sight-sun.jpg'>

URL        `_images/cn-08-sight-arcturus.jpg'
Name       `cn 08 sight arcturus'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1921, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-08-sight-arcturus.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-08-sight-arcturus.jpg'>

URL        `_images/cn-09-sight-arturus-entered.jpg'
Name       `cn 09 sight arturus entered'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1933, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-09-sight-arturus-entered.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-09-sight-arturus-entered.jpg'>

URL        `_images/cn-10-sight-arcturus-calc.jpg'
Name       `cn 10 sight arcturus calc'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1941, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-10-sight-arcturus-calc.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-10-sight-arcturus-calc.jpg'>

URL        `_images/cn-11-sight-kochab.jpg'
Name       `cn 11 sight kochab'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1954, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-11-sight-kochab.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-11-sight-kochab.jpg'>

URL        `_images/cn-12-sight-kochab-calc.jpg'
Name       `cn 12 sight kochab calc'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1966, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-12-sight-kochab-calc.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-12-sight-kochab-calc.jpg'>

URL        `_images/cn-13-fix1-42nm.jpg'
Name       `cn 13 fix1 42nm'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1974, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-13-fix1-42nm.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-13-fix1-42nm.jpg'>

URL        `_images/cn-14-sight-alkaid.jpg'
Name       `cn 14 sight alkaid'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1983, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-14-sight-alkaid.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-14-sight-alkaid.jpg'>

URL        `_images/cn-15-fix2-32nm.jpg'
Name       `cn 15 fix2 32nm'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 1994, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-15-fix2-32nm.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-15-fix2-32nm.jpg'>

URL        `_images/cn-16-fix3-8nm-sun-off.jpg'
Name       `cn 16 fix3 8nm sun off'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 2004, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-16-fix3-8nm-sun-off.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/cn-16-fix3-8nm-sun-off.jpg'>

URL        `_images/fix_42-21.1_-71-6.1.jpg'
Name       `fix 42 21.1  71 6.1'
Parent URL file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/celestial_navigation.html, line 2012, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/fix_42-21.1_-71-6.1.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/celestial_navigation/0.1/_images/fix_42-21.1_-71-6.1.jpg'>

URL        `../install_and_enable.html'
Name       `Install and Enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/polar/0.1/polar.html, line 558, col 8
Real URL   file:///home/runner/work/plugins/plugins/docs/polar/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/polar/install_and_enable.html'>

URL        `_images/polar-load-data.jpg'
Name       `polar load data'
Parent URL file:///home/runner/work/plugins/plugins/docs/polar/0.1/polar.html, line 638, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/polar/0.1/_images/polar-load-data.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/polar/0.1/_images/polar-load-data.jpg'>

URL        `_images/polar-open-file.jpg'
Name       `polar open file'
Parent URL file:///home/runner/work/plugins/plugins/docs/polar/0.1/polar.html, line 646, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/polar/0.1/_images/polar-open-file.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/polar/0.1/_images/polar-open-file.jpg'>

URL        `_images/wdpi-gz-005.jpg'
Name       `wdpi-gz-005.jpg'
Parent URL file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/watchdog.html, line 1984, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-005.jpg
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-005.jpg'>

URL        `_images/wdpi-gz-006.jpg'
Name       `wdpi-gz-006.jpg'
Parent URL file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/watchdog.html, line 1992, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-006.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-006.jpg'>

URL        `_images/wdpi-gz-007.jpg'
Name       `wdpi-gz-007.jpg'
Parent URL file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/watchdog.html, line 2001, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-007.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/watchdog/2.4.29/_images/wdpi-gz-007.jpg'>

URL        `_images/weatherfax.-inetpng.png.detail.html'
Name       `weatherfax. inetpng.png.detail'
Parent URL file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/weatherfax.html, line 628, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/weatherfax.-inetpng.png.detail.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/weatherfax.-inetpng.png.detail.html'>

URL        `_images/wx-b2-ret-hfradiosch-alarmtab-menu.png'
Name       `wx b2 ret hfradiosch alarmtab menu'
Parent URL file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/weatherfax.html, line 724, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b2-ret-hfradiosch-alarmtab-menu.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b2-ret-hfradiosch-alarmtab-menu.png'>

URL        `_images/wx-b3-ret-hfradiosch-captureoptionstab-menu.png'
Name       `wx b3 ret hfradiosch captureoptionstab menu'
Parent URL file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/weatherfax.html, line 732, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b3-ret-hfradiosch-captureoptionstab-menu.png
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b3-ret-hfradiosch-captureoptionstab-menu.png'>

URL        `_images/wx-b4-ret-hfradiosch-infotab-menu.png'
Name       `wx b4 ret hfradiosch infotab menu'
Parent URL file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/weatherfax.html, line 740, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b4-ret-hfradiosch-infotab-menu.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weatherfax/0.1/_images/wx-b4-ret-hfradiosch-infotab-menu.png'>

URL        `../included_plugins/grib_weather.html'
Name       `Grib_pi plugin'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 567, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/included_plugins/grib_weather.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/included_plugins/grib_weather.html'>

URL        `climatology.html'
Name       `Climatology_pi plugin'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 571, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/climatology.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/climatology.html'>

URL        `../../charts/chart_sources.html#high_resolution_background_map'
Name       `GSHHS\nHigh Resolution Background'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 574, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/charts/chart_sources.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/charts/chart_sources.html'>

URL        `../logs/vdr.html'
Name       `VDR_pi'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 601, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/logs/vdr.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/logs/vdr.html'>

URL        `../sailing/polar.html'
Name       `Polar_pi'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 598, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/sailing/polar.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/sailing/polar.html'>

URL        `weather_routing.html'
Name       `Weather_routing_pi'
Parent URL file:///home/runner/work/plugins/plugins/docs/climatology/0.1/climatology.html, line 600, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/climatology/0.1/weather_routing.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/climatology/0.1/weather_routing.html'>

URL        `weather_routing/settings.html'
Name       `Configuration Defaults'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 811, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/settings.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/settings.html'>

URL        `weather_routing/information.html'
Name       `Configuration Terminology'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 814, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/information.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/information.html'>

URL        `../../terminology.html'
Name       `Common Terms'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 815, col 102
Real URL   file:///home/runner/work/plugins/plugins/docs/terminology.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/terminology.html'>

URL        `_images/climatology-wind-setting-100-100.jpg'
Name       `climatology wind setting 100 100'
Parent URL file:///home/runner/work/plugins/plugins/docs/climatology/0.1/climatology.html, line 797, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/climatology/0.1/_images/climatology-wind-setting-100-100.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/climatology/0.1/_images/climatology-wind-setting-100-100.jpg'>

URL        `_images/climatology-wind-rose-settings-125-60.jpg'
Name       `climatology wind rose settings 125 60'
Parent URL file:///home/runner/work/plugins/plugins/docs/climatology/0.1/climatology.html, line 810, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/climatology/0.1/_images/climatology-wind-rose-settings-125-60.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/climatology/0.1/_images/climatology-wind-rose-settings-125-60.jpg'>

URL        `../install_and_enable.html'
Name       `Enable'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 932, col 108
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/install_and_enable.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/install_and_enable.html'>

URL        `boat-test-xml.zip'
Name       `Three Boat.xml zipped files'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 1262, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/boat-test-xml.zip
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/boat-test-xml.zip'>

URL        `weather_routing/polars-pol.zip'
Name       `Polars-Pol.zip'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 1352, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/polars-pol.zip
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing/polars-pol.zip'>

URL        `_images/wr-compute.jpg'
Name       `wr compute'
Parent URL file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/weather_routing.html, line 1512, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/weather_routing/0.1/_images/wr-compute.jpg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/weather_routing/0.1/_images/wr-compute.jpg'>

URL        `assets/JavaScript%20plugin%20user%20guide.pdf'
Name       `Javascript plugin user guide'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/javascript/javascript.html, line 564, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/javascript/assets/JavaScript%20plugin%20user%20guide.pdf
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/javascript/assets/JavaScript plugin user guide.pdf'>

URL        `assets/deviation-compass.doc'
Name       `Draft Functional Specifications by Ozwingle'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/deviation/deviation.html, line 577, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/deviation/assets/deviation-compass.doc
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/deviation/assets/deviation-compass.doc'>

URL        `assets/autopilot_plugin_for_opencpn.docx'
Name       `Docx Documentation'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/autopilot-rm/autopilot-rm.html, line 609, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/autopilot-rm/assets/autopilot_plugin_for_opencpn.docx
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/autopilot-rm/assets/autopilot_plugin_for_opencpn.docx'>

URL        `../plugin_documentation.html'
Name       `here.'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/admiralty/admiralty.html, line 593, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/plugin_documentation.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/plugin_documentation.html'>

URL        `_images/7a.png'
Name       `7a'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/otidalroute/otidalroute.html, line 743, col 24
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/otidalroute/_images/7a.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-beta-plugins/0.1/otidalroute/_images/7a.png'>

URL        `../plugin_documentation.html'
Name       `here.'
Parent URL file:///home/runner/work/plugins/plugins/docs/admiralty/0.1/admiralty.html, line 573, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/admiralty/plugin_documentation.html
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/admiralty/plugin_documentation.html'>

URL        `assets/autopilot_plugin_for_opencpn.docx'
Name       `Docx Documentation'
Parent URL file:///home/runner/work/plugins/plugins/docs/autopilot-rm/0.1/autopilot-rm.html, line 589, col 4
Real URL   file:///home/runner/work/plugins/plugins/docs/autopilot-rm/0.1/assets/autopilot_plugin_for_opencpn.docx
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/autopilot-rm/0.1/assets/autopilot_plugin_for_opencpn.docx'>

URL        `_images/7a.png'
Name       `7a'
Parent URL file:///home/runner/work/plugins/plugins/docs/otidalroute/0.1/otidalroute.html, line 723, col 24
Real URL   file:///home/runner/work/plugins/plugins/docs/otidalroute/0.1/_images/7a.png
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/otidalroute/0.1/_images/7a.png'>

URL        `_images/twocan_screen_2.png.'
Name       `twocan screen 2.png.'
Parent URL file:///home/runner/work/plugins/plugins/docs/twocan/0.1/twocan.html, line 686, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/twocan/0.1/_images/twocan_screen_2.png.
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/twocan/0.1/_images/twocan_screen_2.png.'>
10 threads active,     8 links queued, 1707 links in 1725 URLs checked, runtime 11 seconds

URL        `../../images/local.build.structure.png'
Name       `structure'
Parent URL file:///home/runner/work/plugins/plugins/docs/opencpn-plugins/0.1/authoring/local-build.html, line 826, col 1
Real URL   file:///home/runner/work/plugins/plugins/docs/opencpn-plugins/images/local.build.structure.png
Check time 0.001 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/plugins/plugins/docs/opencpn-plugins/images/local.build.structure.png'>

Statistics:
Downloaded: 3.14MB.
Content types: 891 image, 98 text, 0 video, 0 audio, 22 application, 4 mail and 788 other.
URL lengths: min=16, max=239, avg=81.

That's it. 1803 links in 1803 URLs checked. 1 warning found. 68 errors found.
Stopped checking at 2021-08-14 14:06:17+000 (12 seconds)
