site:
  title: OpenCPN Manuals
  url: https://opencpn-manuals.github.io/plugins
  start_page:  opencpn-plugins::index.adoc

content:
  sources:
    # Keep listed sorted to avoid duplicates and for better diffs.
    - url: .
      branches: HEAD
      start_paths:
      - manual/master-plugins
      - manual/beta-plugins

    # @@plugin-list-begin    Keep this comment, used by main project
    - url: sources/admiralty_tide_tables_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/admiralty_tide_tables_pi/edit/master/{path}

    - url: sources/aisradar_pi/
      branches: HEAD
      start_path: manual/ais_radar_display
      edit_url: https://github.com/opencpn-radar-pi/radar_pi/edit/master/{path}

    - url: sources/Autopilot-Plugin
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/Autopilot-Plugin/edit/master/{path}

    - url: sources/autopilot_route_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/autopilot_route_pi/edit/master/{path}

    - url: sources/AutoTrackRaymarine_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/AutoTrackRaymarine_pi/edit/master/{path}

    - url: sources/calculator_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/calculator_pi/edit/master/{path}      

    - url: sources/celestial_navigation_pi/
      branches: HEAD
      start_path: manual
      edit-url:  https://github.com/rgleason/celestial_navigation_pi/edit/master/{path}

    - url: sources/chartscale_pi
      branches: HEAD
      start_path: manual/chartscale
      edit_url:  https://github.com/rgleason/chartscale_pi/edit/master/{path}

    - url: sources/climatology_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/climatology_pi/edit/master/{path}

    - url: sources/Deviation_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/Deviation_pi/edit/master/{path}

    - url: sources/DR_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/DR_pi/edit/master/{path}

    - url: sources/EngineDashboard
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/EngineDashboard/edit/master/{path}

    - url: sources/EarthExplorer_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/EarthExplorer_pi/edit/master/{path}      

    - url: sources/Findit_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/Findit_pi/edit/master/{path}

    - url: sources/gecomapi_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/gecomapi_pi/edit/master/{path}

    - url: sources/GPS-Odometer_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/GPS-Odometer_pi/edit/master/{path}

    - url: sources/iacfleet_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/nohal/iacfleet_pi/edit/master/{path}

    - url: sources/launcher_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/launcher_pi/edit/master/{path}

    - url: sources/LogbookKonni_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/LogbookKonni_pi/edit/master/{path}

    - url: sources/NmeaConverter_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/NmeaConverter_pi/edit/master/{path}

    - url: sources/ocpndebugger_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/ocpndebugger_pi/edit/master/{path}

    - url: sources/objsearch_pi/
      branches: HEAD
      start_path: manual/objsearch

    - url: sources/ocpn_draw_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/opencpn-manuals/ocpn_draw_pi/edit/master/{path}

    - url: sources/oesenc_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/leamas/oesenc_pi/edit/master/{path}

    - url: sources/otcurrent_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/otcurrent_pi/edit/master/{path}

    - url: sources/otidalplan_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/otidalplan_pi/edit/master/{path}

    - url: sources/otidalroute_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/otidalroute_pi/edit/master/{path}                

    - url: sources/photolayer_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/photolayer_pi/edit/master/{path}

    - url:  sources/plots_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/plots_pi/edit/master/{path}

    - url: sources/polar_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/polar_pi/edit/master/{path}

    - url: sources/projections_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/projections_pi/edit/master/{path}

    - url: sources/pypilot_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/pypilot_pi/edit/master/{path}

    - url: sources/RacingPlugIn
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/RacingPlugIn/edit/master/{path}

    - url: sources/radar_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/opencpn-manuals/radar_pi/edit/master/{path}

    - url:  sources/rotationctrl_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/rotationctrl_pi/edit/master/{path}

    - url: sources/route_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/route_pi/edit/master/{path}

    - url: sources/rtlsdr_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/rtlsdr_pi/edit/master/{path}

    - url: sources/s63_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/s63_pi/edit/master/{path}

    - url: sources/SailawayNMEA_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/SailawayNMEA_pi/edit/master/{path}      

    - url: sources/sar_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/sar_pi/edit/master/{path}

    - url: sources/shipdriver_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/shipdriver_pi/edit/master/{path}

    - url: sources/statusbar_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/statusbar_pi/edit/master/{path}

    - url: sources/survey_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/survey_pi/edit/master/{path}      

    - url: sources/tactics_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/tactics_pi/edit/master/{path}

    - url: sources/TideFinder_pi/
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/TideFinder_pi/edit/master/{path}

    - url: sources/TwoCanPlugIn
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/TwoCanPlugIn/edit/master/{path}

    - url: sources/UKTides_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/UKTides_pi/edit/master/{path}

    - url: sources/vdr_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/rgleason/vdr_pi/edit/master/{path}

    - url: sources/vfkaps_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/Rasbats/vfkaps_pi/edit/master/{path}

    - url: sources/watchdog_pi/
      branches: HEAD
      start_path: manual/watchdog
      edit_url: https://github.com/rgleason/watchdog_pi/edit/master/{path}

    - url: sources/weatherfax_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/weatherfax_pi/edit/master/{path}

    - url: sources/weather_routing_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/weather_routing_pi/edit/master/{path}      

    - url: sources/windvane_pi
      branches: HEAD
      start_path: manual/windvane

    # @@plugin-list-end    Keep this comment, used by main project

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  dir: docs
  clean: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://opencpn-manuals.github.io/plugins/
