= AIS Devices

== Manufacturers

* https://shop.wegmatt.com/[dAISy AIS Receivers]

* https://www.quark-elec.com/product/qk-a026-wireless-ais-gps-receiver/[Wireless AIS+GPS Receiver]

* http://www.comarsystems.com/[Comar]

* http://www.standardhorizon.com/indexVS.cfm?cmd=DisplayProducts&DivisionID=3&ProdCatID=83&ProdID=1769[
Standard Horizon GX2200 Matrix AIS/GPS] +
Dual use of existing VHF antenna, no expensive Coax splitter needed +
Instructions for connection to OpenCPN +
Digikey USB to RS232 Connector to use with the instructions

== AIS Transponders

For https://support.vespermarine.com/hc/en-us/articles/210478206-Configuring-openCPN-for-XB-8000-or-WatchMate-Vision[
Vesper Configuration Instructions with Opencpn]

Also Vesper mobile https://www2.vespermarine.com/xb/apps/[OpenCPN Android App] suggestion

== Vesper XB-8000

https://shop.vespermarine.com/xb8000-ais-transponder[
GPS, AIS Transponder, Wifi, Nmea2000, Nmea0183, Alarm, no screen]

Excellent
 https://panbo.com/vesper-xb-8000-test-much-more-than-a-class-b-ais-transponder/[
Panbo Article on Vesper XB-8000]

== Vesper Watchmate 850

https://shop.vespermarine.com/smartais-transponders/watchmate-vision2[
GPS, AIS Transponder, Wifi, Nmea2000, Nmea0183, Alarm, Screen & Filters]

== AIS Receivers

=== dAISy AIS Receivers

OpenSource. These little receivers work like a charm! A simple and easy
low cost alternative for RPI, USB & Chartplotters.

https://shop.wegmatt.com/[dAISy AIS Receivers -Main Shop Webpage]

* https://shop.wegmatt.com/products/daisy-ais-receiver[dAISy]
  One channel with USB NMEA
* https://shop.wegmatt.com/products/daisy-2-dual-channel-ais-receiver-with-nmea-0183[
  dAISy 2+ with NMEA] output Dual Channel + NMEA RS-422 & USB
* https://shop.wegmatt.com/products/daisy-hat-ais-receiver[dAISy HAT
  for Raspberry Pi] Dual Channel + RPI GPIO pins & RS-422 available.

http://www.wegmatt.com/[dAISy Website]

https://github.com/astuder/dAISy[dAISy Github OpenSource]
https://forum.43oh.com/topic/4833-potm-daisy-a-simple-ais-receiver/[dAISy Early Development]

http://www.cruisersforum.com/forums/f13/daisy-open-source-ais-receiver-154962.html[
Cruiser's Forum Thread]

Examples:

*  https://mvcesc.wordpress.com/2015/04/28/opencpn-on-the-raspberry-pi-2-with-ais/[
   OpenCPN on Rasberry pi 2 with Ais]
*  https://www.hackster.io/mvandervoort/maritime-instrument-display-controller-2b3736[
   A powerful Maritime Instrument & Display Controller- UDIO + dAISy]
*  https://blog.tindie.com/2016/07/track-nearby-ships-using-the-daisy-receiver/[
   Track nearby ships using the dAISy Receiver -Blog]
*  http://pocketmariner.com/daisy-gives-boat-beacon-an-android-ais-answer/[
   Pocketmariner post about dAISy]
*  http://www.wegmatt.com/files/AIS%20over%20WiFi%20with%20the%20DT-06%20module.pdf[
   dAISy2+ -AIS over Wifi with DT-06]

=== Quark A027 GPS AIS Receiver Seatalk Wifi

This Quark unit means that you could use OPenCPN on your laptop and
wirelessly receive all the data from your instruments.
https://www.quark-elec.com/product/qk-a027-wireless-ais-gps-receiver-with-seatalk-converter/[
QK-A027 Wireless AIS Receiver with GPS + SeaTalk Converter] £82.99 There are
other units in their range but this is for Raymarine instrumentation with a
Seatalk enabled unit.

To receive the AIS signals you also need an aerial or you could use a
splitter and use your existing VHF aerial.
https://www.quark-elec.com/product/qk-as02-149-vhf-antenna/?attribute_options=Antenna+%2B+Magnetic+base+with+5+meters+cable[QK-AS02-149-VHF Antenna] AS02-149 = £33.00

https://www.quark-elec.com/product-category/marine/ais-receivers/[
Other Quark AIS Receivers + features]

=== Quark AIS receiver dongle

Quark-elec AIS receiver dongle: Receiving on AIS dual channel alternatively,
USB power and output 3.84k NMEA183 data,Compatible with Windows 7,8,10,
Mac Linux system.
Details : https://www.quark-elec.com/category/marine-electronics-articles/quark-elec-aisnmea-products/qk-a021/

Quark-elec wireless AIS receiver: Receiving on AIS dual channel alternatively, USB power and output 3.84k NMEA183 data.With embedded WiFi module, QK-A023 can share AIS messages with nearby mobile devices wirelessly.
Details : https://www.quark-elec.com/category/marine-electronics-articles/quark-elec-aisnmea-products/qk-a023/

QK-A026 Wireless AIS+GPS Receiver Details : https://www.quark-elec.com/category/marine-electronics-articles/quark-elec-aisnmea-products/qk-a026/

* Quark A026 is about the same price as the Moitessier HAT and provides NMEA 0183 interfaces and WiFi connection
* Self contained, no computer with software needed, just power and VHF/AIS antenna (Vesper splitter)
* Get AIS and GPS info via WiFi to whatever computer, tablet or phone you want.
* Use AIS and GPS info in OpenCPN on a tablet.

=== Sea Angel Mobile AIS - battery powered WIFI AIS Receiver

Standalone battery powered AIS Receiver, WIFI enabled, including VHF Antenna.
Up to 20 hours before it needs recharging and it connects to 10 WIFI clients
simultaneously.  AIS wireless to Opencpn and no mounting on the boat required,
x perfect for all watersport enthusiasts without their own yacht. +
https://seaangel.at/index.php?route=common/page&id=2908

https://seaangel.at/products.2888.html[Sea Angel] Wifi Module, AIS Reciever
USB, AIS MOB Sart.

=== RtlSdr Dongle

There is a plugin which assists with use of this device for AIS purposes. We
have found that for the average user, one of the other low cost choices may
be better.
