= Terminology

== Definitions related to direction and speed as given in Bowditch 2002

Vector;; Any quantity, such as a force, velocity, or acceleration, which
   has both magnitude and direction, as opposed to a SCALAR which has
   magnitude only. Such a quantity may be represented geometrically by
   an arrow of length proportional to its magnitude, pointing in the given
   direction. [Dutch: vector]

Velocity;;
   A vector quantity equal to speed in a given direction. [Dutch: snelheid
   (in een bepaalde richting)]

North;;
   The primary reference direction relative to the earth; the direction
   indicated by 000° in any system other than relative. True north is the
   direction of the north geographical pole; magnetic north the direction
   north as determined by the earth’s magnetic compass; grid north an
   arbitrary reference direction used with grid navigation. [Dutch: noord,
   noorden, N]

True North;;
   The direction of the north geographical pole; the reference direction for
   measurement of true directions. [Dutch: ware noorden, Nw]

Variation;;
   The angle between the magnetic and geographic meridians at any place,
   expressed in degrees and minutes east or west to indicate the direction
   of magnetic north from true north. The angle between magnetic and grid
   meridians is called GRID MAGNETIC ANGLE, GRID VARIATION, or GRIVATION.
   Called MAGNETIC VARIATION when a distinction is needed to prevent possible
   ambiguity. [Dutch: variatie, var]

Magnetic North;;
   The direction indicated by the north seeking pole of a freely suspended
   magnetic needle, influenced only by the earth’s magnetic field. [Dutch:
   magnetische noorden, Nm]

Deviation;;
   The angle between the magnetic meridian and the axis of a compass card,
   expressed in degrees east or west to indicate the direction in which the
   northern end of the compass card is offset from magnetic north. Deviation
   is caused by disturbing magnetic influences in the immediate vicinity of
   the compass. Semicircular deviation changes sign (E or W) approximately
   each 180° change of heading; quadrantal deviation changes sign
   approximately each 90° change of heading; constant deviation is the same
   on any heading. Deviation of a magnetic compass after adjustment or
   compensation is RESIDUAL DEVIATION. Called MAGNETIC DEVIATION when a
   distinction is needed to prevent possible ambiguity. [Dutch: deviatie, dev]

Compass North;;
   The direction north as indicated by a magnetic compass; the reference
   direction for measurement of compass directions. [Dutch: kompasnoorden, Nk]

NOTE:
Variation is the same as Declination See NOAA Geomagnetism and Wikipedia
“Declination” (magnetic affects of the world) should not be confused with
“Deviation” (magnetic effects of the ship). That is the reason we are using
the word Variation exclusively, as Bowditch does, for clarity and lack of confusion.
Nautical Acronyms

== Definitions

The definitions below are for those terms commonly used in instrument systems and
navigation. The abbreviations shown are those more commonly used and may vary from
one manufacturer to another. The definitions likewise may vary.

Route (RT);;
   A route is a predefined path or passage from one point to another. Routes
   generally use a series of Marks or Waypoints at each course change.
   Waypoints are Location Markers with specific Longitude and Latitude.
   The Route Legs between the Waypoints each have a specific Course and Distance.

Waypoint (WPT);;
  A waypoint marks a specific location, coordinates, or Latitude and Longitude,
  often determined by GPS. A Waypoint could be considered the ending point of
  a Leg.

Isochrones;;
  While calculating a Weather Routing the plugin will calculate the location
  of the boat for a given time interval (eg: 1 hr, 4hr, 6 hr or 12hr ) and
  an isochrone represents how far the boat willl sail in a given direction,
  based on the weather and boat conditions, for each successive time interval.
  Isochrones are like contour lines around the starting point. Think of them
  as showing an intermediate destination, and the calculated distancee traveled.

Apparent Wind (AW);;
  Wind speed and direction relative to the boat. Apparent Wind is measured in
  the frame of reference of the boat, which may be subject to boat movement
  through the water (propulsion by sails, engine, etc) and movement of the body
  of water itself (currents, tides, etc). Apparent Wind is relative to the boat.

Apparent Wind Direction (AWD);;
  Compass direction from which the wind is coming relative to the boat.

Apparent Wind Angle (AWA);;
  Apparent Wind Angle is expressed in angle to the bow of Ownship, in degrees
  to port or starboard of the Heading, as measured by the onboard wind instrument.

Apparent Wind Speed (AWS);;
  Wind speed relative to the boat as measured by the onboard wind instrument

Average Speed (AVS);;
  Average Boat Speed through the water. (Trip Log / Trip Time)

Bearing to Waypoint (BTW);;
  Compass bearing to active waypoint measured from the current position.

Bearing Waypoint to Waypoint;;
  Compass bearing to a waypoint measured from the previous waypoint.

Boat Position (POS);;
  Latitude and Longitude of the boat

Boat Speed (BSP or STW);;
  Sometimes called Speedo Speed of the boat through the water as measured by
  the onboard speed transducer.

Compass Course (CC);;
  The course steered from the magnetic compass using adjustments for True,
  Variation and Magnetic Deviation values.
  True-Variation-Magnetic-Deviation-Compass (TVMDC) values.
Course (CRS);;
  Compass direction that the boat is moving through the water (HDG + Leeway).
  Note that the difference between CRS and COG is Current. CRS does not
  include the effect of current.

Course to Steer (CTS);;
  The course to steer to offset the effect of currents, wind and other factors.

Speed to go (STG);;

Course Over Ground (COG);;
  Actual Compass direction that the boat is moving over the surface of the
  earth. (HDG + Leeway + Current) “The actual course you are moving along
  at the moment relative to the fixed land, meaning actual direction you
  travel regardless of the course steered and temporary variations in heading
  around this course. Things that cause COG to differ from heading include:
  current, leeway, poor helmsmanship, or compass errors.” Often derived from GPS.

Speed Over Ground (SOG);;
  The speed actually achieved which includes the effect or current set
  (direction) & drift (speed), wind and leeway and helmsman errrors. Same as
  SMG. Often derived from GPS.

Course Made Good (CMG);;
  Is the course actually steered which includes the effect of current set
  (direction) & drift (speed), wind and leeway and helmsman errrors. Note
  we distinguish COG (course over ground) from cmg (course made good), as one
  being present dynamic value, and the other being past. The phrase “course
  made good,” can be used to refer to a single track line or to the
  combination of several course changes between two points. If i sailed 1
  mile north and 1 mile east, i made good a course of 045. Or, if i tried
  to sail course 200 but was being set between 10 and 20°, then i might end
  up “making good a course” of say 214. The distinctions between terms is not
  often critical, but may help to clarify some communications.

Speed made good (SMG);;
  The speed actually achieved which includes the effect or current set
  (direction) & drift (speed), wind and leeway and helmsman errrors.

Cross Track Error (XTE);;
  The perpendicular distance from the direct route (rhumb line or great
  circle) between two waypoints to the current position of the boat (POS)

Dead Reckoning, also Ded Reckoning (DR);;
  Dead reckoning is the process of determining one’s present position by
  projecting known or estimated course(s) and speed(s) from a known past
  position, or predicting a future position by projecting known or estimated
  course(s) and speed(s) from a known present position. The DR position is
  only an approximate position.

Drift (DFT);;
  Speed that the water is moving. This movement may be caused by a number
  of factors, including; tide, ocean currents, river flows etc.

Electronic Chart Display & Information System (ECDIS);;
  An ECDIS is a computer-based navigation information system that complies
  with International Maritime Organization (IMO) regulations and can be used
  as an alternative to paper nautical charts. IMO refers to similar systems
  not meeting the regulations as Electronic Chart Systems (ECS)

Electronic Navigational Chart (ENC);;
  An ENC is an official database created by a national hydrographic office for
  use with an ECDIS. An ENC must conform to standards stated in the
  International Hydrographic Organization (IHO) Special Publication S-57
  before it can be certified as an ENC. Only ENCs can be used within ECDIS
  to meet the International Maritime Organisation (IMO) performance standard
  for ECDIS.

Ground Wind (GW);;
  Wind speed and direction relative to the ground (same as landspeople’s
  true wind). Ground Wind direction is expressed in compass direction.
  Ground Wind speed and direction is also relative to boats anchored or
  moored and stationary relative to the earth. Ground Wind is used in weather
  forecasts and reports.

Ground Wind Direction (GWD );;
  Wind direction relative to the ground (same as landspeople’s true wind).
  Ground Wind direction is expressed in compass direction.

Ground Wind Speed (GWS);;
 Wind speed relative to the ground.

Heading (HDG, HDT, HDM);;
  Compass direction in which the boat is pointed. The abbreviations HDT and
  HDM are typically used to distinguish between heading degrees true and
  heading degrees magnetic, whereas HDG does not infer either a true or a
  magnetic heading. Whether HDG displays true or magnetic values, will
  depend on sensor selection and system setup.

Heel (HEL);;
  Heeling Angle in degrees of the port/starboard inclination of the boat.
  Heeling angle is associated with the boat's lateral movement, or Leeway

Layline;;
  Theoretical COG that will be achieved if the current conditions (TWD, TWS,
  TWA, SET, DFT, BSP, HEL etc), remain constant. There are port and starboard
  laylines that represent port and starboard tacks (or gybes). There are boat
  laylines, which emanate from the boat, and waypoint laylines, which emanate
  from the active waypoint. They are used to indicate when it is beneficial to
  tack or gybe.

Leeway;;
  Leeway is the angle between the HDG and the CRS and results from the lateral
  movement experienced by the boat as she moves forward through the water..
  The empirical formula is that
  Leeway = -1 * k * Heel / BSP^2^. The formula itself is often called into
  question, especially with planning hulls. The k value, which is boat
  specific, will vary according to crew numbers and boat loading.

Log (LOG);;
  Record of distance travelled

NMEA National Marine Electronics Association has several standards NMEA0183
and NMEA2000. Nmea2000 uses manufacturer PGN's. Two Links for Nmea 0183 NMEA0183
Sentences and NMEA0183 Revealed

Set (SET);;
  Compass direction of moving water (In the direction of the moving water).
  This movement may be caused by a number of factors, including; tide, ocean
  currents, river flows etc.

Speed Over Ground (SOG);;
  Speed that the boat is moving over the surface of the earth or ground.

Speed Polars;;
  Theoretical values for maximum BSP for a range of given TWSs and TWAs.

Target (Boat Speed);;
  (BSP) Theoretical values for TWA and BSP for a range of given TWSs that
  result in the highest VMG. It is derived from the Speed Polars.
  https://sailzing.com/velocity-made-good-vmg/

Track (TRK);;
  A record of the ships position as it proceeds on its voyage.

True Wind (TW);;
  Wind speed and direction relative to the surface of the water. Sailors
  sail in the interface between air and water, therefore mariners' True Wind
  is relative to water and different from landspeople’s true wind. True wind
  is perceived when the boat is stationary in the water, but moving with the
  tide or current; similar to the wind in the plane of reference of a stick
  floating down a river. True wind is not adjusted for current, tide or
  leeway, and that is how Ground wind differs.

True Wind Direction (TWD);;
  Compass direction from which the wind is coming over the surface of the water.

True Wind Angle (TWA);;
  True Wind angle is typically expressed as angle to the bow of Ownship.
  Note that mariners use the expression Wind angle relative to the bow in
  degrees to port or starboard of CRS (some instrument systems do not consider
  leeway in the calculation of TWA and in this case TWA is the wind angle
  relative to the bow in degrees to port or starboard of HDG).

True Wind Speed (TWS);;
  Wind speed over the surface of the water.

Velocity Made on Course (VMC);;
  Speed achieved directly toward the active waypoint. The value of VMC changes
  the longer the tack. VMC decreases the greater the angle to the mark, until
  on the layline where it turns to “0” and then starts getting negative
  because the distance from the mark is increasing.

Velocity Made Good (VMG);;
  Speed achieved directly towards, or away from, the TWD. The average value
  of VMG is an indicator of optimum sailing angle, and should be used as a
  general indicator, however the skipper should be using Target Boat speed
  to sail at the optimum tacking angel. https://sailzing.com/velocity-made-good-vmg/

Estimated Time of Arrival (ETA);;
  ETA is not an accurate way to judge progress or performance in a tacking
  sailboat because it does not account for the greater distance sailed between
  waypoints. VMC (to Waypoint or Course) changes the longer the tack is
  (VMG decreases dramatically as the boat gets to the 'layline' for the mark,
  because of the increased angle from the mark) and VMG (to Wind) has similar
  problems because it is not relative to a destination. So these terms are
  not effective for sailing.

Tacking Time to Destination (TTD);;
  Calculates in advance how long it will take to tack (or jibe) a sailboat
  to a particular destination in particular wind conditions, including
  factors such as wind changes, currents, waves, boat polars, sail and boat
  bottom conditions. An approximation of performance. [From Sailtimer
  documents]. Tacking Time to Destination TTD may also provide a better
  measure of performance than ETA and VMG. Tacking performance is commonly
  judged by using Target boat speeds now.

Time to go (TTG);;


Turn Rate;;
  The AIS class A “Turn rate” signal normally comes from a gyro or satellite
  compass. It's not calculated by the AIS itself.

Heading Rate;;
  Heading rate is the rate of the heading which is typically derived from a
  magnetic compass. This is the absolute orientation of the boat.

== L-36 Sailing Terminology - Extensive list.

[%autowidth]
|=============================
| AWA | Apparent Wind Angle
| AWD | Apparent Wind Direction
| AWS | Apparent Wind Speed
| GWA | Ground Wind Angle
| GWD | Ground Wind Direction
| GWS | Ground Wind Speed
| TWA | True Wind Angle
| TWD | True Wind Direction
| TWS | True Wind Speed
| VMC | Velocity Made Good (to Waypoint, course)
| VMG | Velocity Made Good (to Wind)
| POS | Boat Position
| SPD | Boat speed thru the water
| SOG | Speed over ground -Gps
| COG | Course over ground (Includes the effect of HDG + Leeway + Current) -Gps
| CRS | Course - Compass direction that the boat is moving through the water (Includes effect of HDG + Leeway).
| HDG | Heading Compass direction in which the boat is pointed.
| HDT | Heading Compass True direction in which the boat is pointed.
| HDM | Heading Compass Magnetic direction in which the boat is pointed.
| DFT | Drift -Speed that the water is moving.
| SET | Compass -Direction water is moving towards
| LOG | Record of distance travelled
| XTE | Cross track error
| ETA | Estimated time of Arrival
| TTG | Time to Go
| BSP | or Target Boat Speed for various points of sail in various winds for optimal performance.
| TTD | Tacking time to Destination
| Leeway | Angle between the HDG and the CRS
| Track |
|=============================
