= RPI Setups & Accessories
== RPI Marine Setups

*  OpenPlotter Hardware
   https://www.youtube.com/watch?v=qbVuFEpTjuc[]
*  OpenPlotter install
   https://www.youtube.com/watch?v=C9DKu0P7-tM[]
*  How to Sail Digital for CHEAP with Raspberry Pi
   https://www.youtube.com/watch?v=U3ucE3Rx7Tw[Sailing Balachandra S02E32]
*  RPI Display and OpenCPN https://www.youtube.com/watch?v=BKtBKVCWMy4
*  Openplotter instruction video for Raspberry Pi
   https://www.youtube.com/watch?v=r8CGixMl18k
*  Building your own Chartplotter with a Raspberry Pi and OpenCPN
   https://www.youtube.com/watch?v=PdfLTA2CRL8
*  zeilersforum.nl Serious Chartplotter Setup
    https://zeilersforum.nl/index.php/forum-hoofdmenu-37/raspberry-pi-arduino-etcetera/586581-rpi-als-boordcomputer?start=%1$d
*  Mgrouch Docs & photos of navigation system with OpenCPN/openplotter
   https://bareboat-necessities.github.io/my-bareboat/
*  BBN Marine OS for raspberry pi now released as Stable. Includes OpenCPN,
   SignalK, PyPilot, and more info, Getting Started Guide. Download links
   here: https://github.com/bareboat-necessities/lysmarine_gen
*  Sailing Belachandra Installation & 2 year review
   https://www.youtube.com/channel/UCT_tWXWJCUAI17XUYfe-1Bg/search?query=opencpn[
   RPI3B, Openplotter & Opencpn Videos (2)]

== User Guides for RPI

http://svmatilda.blogspot.com/2018/11/setting-up-our-raspberry-pi-with.html[
SV Matilda - Set up RPI with OpenPlotter]

== DC Power Supply

https://www.meanwell.com/webapp/product/search.aspx?prod=SD-25[
Meanwell SD-25 25watt]


== RPI Examples - What you can do

http://www.lediouris.net/RaspberryPI/_Articles/readme.html[
Enriching an NMEA Stream]

== Intel Atom Alternative to RPI (low power)

Intel Atom based minicomputers are phenomenally low powered and have no fans.
Use maximum <5 watts while watching 4K movies, and normally about 3 watts when
in use, not idle. I connect the box directly to ship's 13.6v power supply
with no dropper or stabilizer.


== ROCK64 4K60P HDR Media Board Computer

Some users are using a Rock64. ROCK64 is a credit card size 4K60P HDR Media
Board Computer powered by Rockchip RK3328 Quad-Core ARM Cortex A53 64-Bit
Processor and support up to 4GB 1600MHz LPDDR3 memory. It provides eMMC
module socket, MicroSD Card slot, Pi-2 Bus, Pi-P5+ Bus, USB 3.0 and many
others peripheral devices interface for makers to integrate with sensors
and devices. Various Operating System (OS)

== Monitors
=== Sean on monitors

I read it's possible to convert any screen by just using a more powerful
backlight. You can buy LEDS of the right type, and install them to greatly
increase backlight power. I think this will use a lot of power. The only
alternative is transreflective?? This costs a lot.

I think I will keep the screen inside the boat and not worry about it.
Maybe it's too far away on a bigger boat, but for me, I can see the inside
screen fine sitting outside. I'm too worried about waves splashing it anyway.

=== Cheap Daylight Viewable Monitors

See CruiserForum Discussions:

* http://www.cruisersforum.com/forums/f134/need-cheap-daylight-viewable-monitor-59672.html[
Cheap Daylight Viewable Monitor]

* http://www.cruisersforum.com/forums/f134/raspberry-screen-power-source-and-housing-195036.html[
Raspberry Screen, Power Source & Housing]

Cheaper but (too) small monitor where you must build your own waterproof
chassis. Adafruit HDMI 4 Pi - 10.1" Display 1280x800 IPS, HDMI/VGA/NTSC/PAL,
PROD ID: 1287 $144.95

https://www.faytech.us/touchscreen-monitor/industrial/[
Faytech Industries, 7"-15", IP65, 8-36VDC, 7-24W, Resistive (some capacitive)
Touchscreens(USB), 1000Nit, VGA or HDMI]
$225-$590 USD. - The 10“ Faytech touchscreen works very well and is a rigid
 construction in an alu housing. Available with VGA or HDMI and it works
 with Raspberry PI. - Faytech screen is three times brighter and comes
 waterproof as standard. The Faytech has two buttons (+/-) on the front
 panel, so that you can easily change the light intensity, and the power
 consumption is only 10 watts. In combination with my Raspberry Pi it has
 a very low power consumption. Low intensity backlight 4.8 watts and high
 intensity backlight 7.8 watts, with the screen connected to a 240/12 volt
 adapter. See
https://www.cruisersforum.com/forums/f134/need-cheap-daylight-viewable-monitor-59672.html#post2504172[
Bram's Post]

Comparison: $145. vs. $270.

For $125 extra you are getting:

. Uses only 10 watts
. 1000 nits brightness vs 350
. LEDs for screen lighting
. USB touchscreen
. Full IP65 Waterproof enclosure
. Wide input power 8-36V
. Wide operating temperature range.
. Waterproof speakers, integral and work via the HDMI cable.
. Cable harnass (HDMI, USB (touchscreen) & Power cable is around 1.80 meter.
. 2 versions VGA or HDMI
. Brightness adjustment in front with +/- button.
. Remote Control
. Stylus

https://www.faytech.com/product/touch-monitor/open-frame-touch-monitors/7-open-frame-capacitive-touch-monitor/?fbclid=IwAR372D4u-j-rgwYEOUm8ZsIano8xbFJM6bP89y5xTuvgrcLeCg_3pK9Eq4c[
Faytech 7″ Open Frame Capacitive Touch Monitor]

https://botland.store/raspberry-pi-cm/20050-industrial-pi-cm4-70-em-raspberry-pi-cm4-compute-module-4-7-display.html[
Industrial Pi CM4-70-EM - Raspberry Pi CM4 Compute Module 4 + 7'' display]

Other comments:

. Txg - We use a 13” with 1920×1080, no issues with scaling and uses less
  than 6W at full brightness (only about 250nits but thats fine below deck).
. Sean -My screen cost less than half what yours does, but the resolution is
  only 1366×768. 16” hdmi display runs directly on 12v (11-15v so far no
  problem) uses 350mA. Sceptre E165W-1600HC E 16“ Screen LED-Lit Monitor,
  True Black (E165W-1600HC)
. Tupaia -Eyoyo/Lilliput A7S 7” monitor for cockpit, field monitor used by
  photographers, Size: 7 inch, Resolution: 1920×1200, Connection: HDMI,
  Power: 7-24 volt, Consumption <11W, Brightness: 500 cd/m2, Contrast:
  1000:1. Comes with a removable rubber surround for protection and a sun
  hood. I am very pleased with the results and it was reasonably priced at
  US$150. It is not quite as bright as Nexus 7, first choice for drones, but
  the 500 cd/m and the contrast ratio makes it is one of the brightest I
  could find, especially for the price and it is pretty good. The screen is
  gloss so there are some reflections in certain conditions although the hood
  that comes with it works well in these circumstances. Because it is a
  camera monitor it has lots of functions that aren't relevant but there is a
  thumb wheel “brightness” adjust and you can set one of the 2 function
  buttons to “Scan” that effectively zooms the central section of the screen
  very useful on a 7“ screen.
. On my Raspberry Pi 2 with the official Pi 7” touch screen the Chart
  Downloader plugin is unusable. The “New Chart Source” window opens with
  the catalogue pane overwritten by the Chart Directory selection box. There
  is plenty of screen real estate available. There doesn't seem to be anyway
  available to resize the window. I have to use a PC and copy the chart files
  over.
. Lilliput A7S screen (500nits) which initially was great in our cockpit
  (500nits), but the problem is that with polarized sunglasses all you see is
  a black screen. FYI this screen is not waterproof, but it can be fixed.

AndersG reports ..I am happy with the Lilliput A7S 7“ 1920×1200 500 nits
photo field monitor. Some with say not bright enough but I disagree. Also
x high resolution makes up for small screen size… 12V OK… $155 from Amazon.
I taped all the vents up and it ran OK for days (a bit hot but not too hot),
so I am going to try and weatherproof it now.

For Small Touch Screens look at https://smallhd.com/[SmallHD]. These are
high end field and production monitors, with HDMI,sdi and wireless interfaces.

== Display for bright sunlight

Brightness needs to be 1000+ nits

Brightness of 300 nits is just not enough. Typical, cheap, color
chartplotters have a screen that specs out at 750 nits as a minimum;
usually closer to 1000 nits. Can you “make do” with a 300 or 500 nit screen?
Sure. That's about usual for a decent phone screen, and they work reasonably
well in sunlight. But compare the screen on your phone to one on even a very
cheap chartplotter and you will clearly see a significant difference. When
you need the chartplotter you must see is clearly and easily.

http://www.cruisersforum.com/forums/f134/sunlight-viewable-monitor-202821.html#post2654623[
Verkerber wrote]:

10” Faytech monitor, daylight, water resistant and touchscreen. HDMi version.
Works very well. For the touch screen you need the Egalax driver and change
some settings. Works with two versions of OpenCPN. One with the detail chart
and one with the overview.

FT10MBIP65HDMI -10“ IP65, High brightness cd/m2 1000+ nits, with two speakers,
using HDMI cable for AIS alerts and playing music. Brightness setting on the
front panel. Has led backlight. 12 volt. Power consumption in combination
with the PI is around 10-12 watts. Has touch function (no gesture) with an
Egalax driver. I have here the instructions on how to do that. It is not
simply installing the Eeti driver. Bought the monitor in Germany at HRT.

Monitor has vesa mounting points and a support is not included. I use a Ball
pivot Ram support, which is nice and rigid. I use an extra ball to have the
monitor available on two places. I'am using the screen in combination with
my RPI3B+. With latest updates and latest kernel. VC4 driver on. Running now
with the glxgears test at around 1000 FPS. Price in 2017 was € 308,-
including VAT and freight.

See photos in the link above. Or the Faytech 15” IP65 High brightness Touch.

For visibility, check out screens used as remote control for serious dslr and
video shooters. Best DSLR Camera Monitors will have recent reviews, but such
devices cost $$ while all it takes is an OpenCPN or any other free nav app
on a sub 100 USD table, (even mirroring the RPI with VNC) . Hard to beat the
buck factor. (Barnakiel)

https://www.facebook.com/groups/1666364153609573/permalink/2775226739389970/[
Mikhail Grushinskiy] shared a good https://m.alibaba.com/product/62059970636/Good-quality-marine-navigation-system-touchscreen.html?__sceneInfo=%7B%22type%22%3A%22appDetailShare%22%2C%22data%22%3A%7B%22filterKey%22%3A%227.8.2_share%22%2C%22cacheTime%22%3A%221800000%22%7D%7D&fbclid=IwAR2s1QHfGKvIwEU0-V3JTc2UGXfCpO06K4SVPgLmGPpSTdz-Np6yS6PtNbM[Display Good Quality Marine Nav Display] 7 inch IP65
waterproof Industrial embedded Capacitive Touchscreen Monitor 600cd/m2 (nits)
(standard) doesn't make it much brighter than an iPad (Just ask for a
brighter one of 1000+ nits). Only the screen part is waterproof (not a
problem really), 1024×600. Variable 500nit-1500nit LED backlights.

== Touchscreen (Daylight & Waterproof) & Software

See Mgrouch CF Post #4 in
https://www.cruisersforum.com/forums/f134/open-cpn-on-a-touchscreen-244005.html#post3302330[
OpenCPN on a Touchscreen] Mounted in the cockpit with cable to RPI inside
cabin
https://www.sihovision.com/industrial-touch-monitor/7-inch-industrial-wide-temperaturer-lcd-monitor-with-remote-control-1.html[
Waterproof IP65 7" 1024x600 Industrial wide temperature LCD monitor
brightness 1000nit with Touch Capacitive Screen]

Mgrouch provides modified OpenCPN software with TouchSreen enabled in
https://www.cruisersforum.com/forums/f134/open-cpn-on-a-touchscreen-244005.html#post3302330[Post #5]

== Display for Cabin

13“-19” Samsung LED HD (720p) with 2 HDMI, USB, Coax, Component Analog Video
(possibly VGA or DVI if needed) Under $130 You want LED as they use less and
you must have HDMI for the RPI. The issue here is how to power with 12vDC.
Two answers:

19“ and just goes straight into the boat 12v supply (sometimes 15v) draws about 1A.
Small pure sine wave inverter, overkill at 150 Watts but allows for other low power devices. $150 on eBay. 32 inch LCD uses 40 Watts.

High power, sun readable displays are difficult to come by. I purchased a second hand Raymarine A65 for its 6.5” quality display, it turned out to be just 400 nits. So we have to compromise a bit, put it in the shade or something. In terms of water proofing, my suggested approach is to build your system and then cover all the edges of the display/components with silicone. Definitely go for cheaper displays and replace often vs. buying one expensive display.

== VNC - Another Viewpoint about Monitors

A tablet on it's own has just a tiny fraction of the capabilities of having a
Pi running openplotter providing data to a tablet. Add from a large
selection of cheap sensors for barometer, voltage, current, temperature;
multiplex it all over wifi as signalk & nmea, record everything into a
database & view easily in a web browser; wifi access point repeater, decode
wfax, music system, the list goes on for not a lot of cost and mostly menus
to set up. No need for a monitor, set it all up with VNC on a tablet. (Conachair)


== SSD Card

* http://www.cruisersforum.com/forums/f134/raspberry-pi-w-opencpn-208244.html#post2734168[
  CF Post by BenS]
* https://www.conrad.com/p/m2-sata-ssd-expansion-board-for-the-raspberry-pi-1487097[
  M.2 SATA SSD expansion board for the Raspberry Pi]
* https://www.aliexpress.com/item/1005001504728181.html?spm=a2g0o.detail.0.0.13ed7387LeWuu7&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.169870.0&scm_id=1007.13339.169870.0&scm-url=1007.13339.169870.0&pvid=a350fa0c-fe24-42c0-945e-6aacbb697da5&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.169870.0,pvid:a350fa0c-fe24-42c0-945e-6aacbb697da5,tpp_buckets:668%230%23131923%2339_668%23888%233325%2319_668%232846%238113%23699_668%232717%237563%23552_668%231000022185%231000066058%230_668%233468%2315617%23877[
RPI4 52Pi X862 M.2 2280/2260/2242/2230 SATA SSD Shield, X862 SSD Storage Expansion Board]
RPI1234 52Pi X828 Stackable 2.5" SATA HDD/SSD Shield Expansion Board USB3.0 Hub]

== Power & UPS

* Having adequate power supply is essential.
* https://www.tindie.com/products/silicognition/lifepo4weredpi-2/[Power and UPS]
* RPI4 Low Power
* RPI4 UPS from 52pi 52Pi https://www.aliexpress.com/item/33012132000.html?spm=a2g0o.detail.100009.3.6c68286dn1orHn&gps-id=pcDetailLeftTopSell&scm=1007.13482.95643.0&scm_id=1007.13482.95643.0&scm-url=1007.13482.95643.0&pvid=ea369137-0116-4cfe-99ab-bdaa8f7e215f&_t=gps-id:pcDetailLeftTopSell,scm-url:1007.13482.95643.0,pvid:ea369137-0116-4cfe-99ab-bdaa8f7e215f,tpp_buckets:668%230%23131923%2377_668%23888%233325%2319_668%232846%238113%23699_668%232717%237563%23552_668%231000022185%231000066058%230_668%233480%2315683%23541[
Original New UPS With RTC & Coulometer Pro Power Supply Device]

== Cooling - Natural, Fan, ICE

* https://www.aliexpress.com/item/4000288119233.html?spm=a2g0o.detail.100009.1.713c7387esN1mC&gps-id=pcDetailLeftTopSell&scm=1007.13482.95643.0&scm_id=1007.13482.95643.0&scm-url=1007.13482.95643.0&pvid=3ea34b32-d492-4aab-a634-e9ebb75b5e44&_t=gps-id:pcDetailLeftTopSell,scm-url:1007.13482.95643.0,pvid:3ea34b32-d492-4aab-a634-e9ebb75b5e44,tpp_buckets:668%230%23131923%239_668%23888%233325%2319_668%232846%238113%23699_668%232717%237563%23552_668%231000022185%231000066058%230_668%233480%2315683%23815[
RPI4 52pi Cooling Tower Low-Profile ICE-Tower CPU Cooling Fan for Raspberry Pi]
* https://www.amazon.com/Raspberry-Cooling-Automatic-Discoloration-Expansion/dp/B08B111D8K/ref=pd_di_sccai_6?pd_rd_w=miFok&pf_rd_p=c9443270-b914-4430-a90b-72e3e7e784e0&pf_rd_r=J4GDBHAHX6PMCWJGESZ6&pd_rd_r=240f7b6c-c385-4b6e-9162-325950af5231&pd_rd_wg=3k2sg&pd_rd_i=B08B111D8K&psc=1[
PI1234 Dual Cooling Fans Dual Fans]

== Inertial Measurement & Fluxgate Compass

B&G Precision 9 Compass $650 or the All-in-one GPS + IMU Airmar GH2183 $800
https://www.defender.com in terms of accuracy, use with Radar Overlay, Arpa,
Marpa, measurement of heeling angle and as bcn suggests leeway?

* Moo advises: In terms of accuracy it is probably not bad. But it is not a
  comparable product. The others are purpose built with NMEA outputs ready
  for network integration whilst the MPU-9255 is just the sensor and a few
  components to interface it to a bus.
* Håkan advises: I'm using this setup for my system and it works good enough
  for radar and ARPA. The compass sensor is rather equal to the MPU-9255 I
  suppose. See:
  http://www.cruisersforum.com/forums/f134/inexpensive-heading-sensor-103042.html#post1495725[
  Inexpensive heading sensor]? Heading data is sent by 2 Hz but
  OCPN is receiving at 1 Hz, probably due to 1 Hz system bus on the Simrad
  IS15 system. On a low speed sailing boat the 1 Hz update is apparently
  sufficient. Håkan's post has 3 pdfs showing the Arduino.

== Wireless Trackball

https://support.logitech.com/en_us/product/wireless-trackball-m570[
Logitech Wireless Trackball m570]

== Adding a Real Time Clock

https://thepihut.com/blogs/raspberry-pi-tutorials/17209332-adding-a-real-time-clock-to-your-raspberry-pi

== AIS

https://www.tindie.com/products/astuder/daisy-hat-ais-receiver-for-raspberry-pi/?gclid=Cj0KCQjw95vPBRDVARIsAKvPd3JLjy2Yc8hUB2CYkmapCyJ3sHyhOj7TLrxclVJnJpHcuOcP7Lwdl-MaAuf4EALw_wcB[dAISy HAT for RPI] $65

== PyPilot Autopilot

An OpenSource Marine Autopilot. Tested pypilot on a trimaran sailing 15 knots, and it is working.

* https://www.pypilot.org/[Website (Hardware and Software)]
* https://github.com/pypilot/pypilot[Github (Python & C++)]
* https://github.com/pypilot/pypilot/wiki/Hardware[Hardware]
* http://phoenixketch.blogspot.com/search/label/Autopilot[PhoenixKetch Pypilot]

PyPilot Forums

*   http://www.cruisersforum.com/forums/f134/autopilot-open-source-191315.html[
    Cruiser's Forum Autopilot - Open Source]
*   https://forum.openmarine.net/forumdisplay.php?fid=17[
    PyPilot OpenMarine Forum]
*   http://www.cruisersforum.com/forums/f13/free-autopilot-186378.html[
    Cruiser's Forum Free Autopilot Discussion]

Sean D'Epagnier's PyPilot AutoPilot using raspberry zero-W or orange,

*   https://github.com/pypilot/pypilot/wiki/controller[Controller]
*   https://github.com/pypilot/pypilot/wiki/LCD_keypad[
    Optional user interface LCD and keypad], gps and weather sensors.

https://github.com/pypilot/pypilot/wiki/webapp[Pypilot Webapp] if using
tinypilot, creates a webserver which provides remote autopilot control
through a browser. Trimaran test used rtlsdr IR remote for control. It can
use any tv remote, also buttons, or gui program through openplotter.

This Autopilot uses modified and improved versions of SignalK and RTMUlib2.
More details are available in the Wiki and README


https://www.tindie.com/stores/seandepagnier/[Tindie Store]

== Pypilot Requirements

Literally requires some Raspberry Pi, an IMU and a motor controller.
https://www.cruisersforum.com/forums/f134/b-and-g-triton-236323.html#post3175756

There should be some NMEA0183-IN for the pypilot, since you want to steer on
apparent wind, but that can also be provided over the network (kplex or
signalk 10110). If OpenCPN and SignalK works on one computer, you use
tinypilot (pypilot on a seperate pi) and they can be connected using wifi.
If you use OpenPlotter you can also install pypilot to the same pi where you
use OpenCPN adding the IMU and the controller to OpenPlotter.

First diagram:

```
Sensors (wind) =nmea=>  pc (SignalK + Opencpn) =wifi=> tinypi   <=i2c= IMU
                                                       ||  /\
                                                       \/  ||
                                           motorcontroller   rudder feedback
```

Second diagram

```
Sensors (wind) =nmea=>  pc (SignalK + Opencpn) <=I2C= IMU
                           ||         /\
                           \/         ||
                 motorcontroller   rudder feedback

```

You could also use the tinypi as central computer in the network (not my preference).

== Rudder Sensor

https://www.amazon.com/VDO-Single-Station-Rudder-Sensor/dp/B07J2VMJ1S[
VDO Single Station Rudder Angle Sensor - 12/24V - 10-180 OHM A2C1102950001]

https://www.cruisersforum.com/forums/f134/rudder-position-pypilot-238333.html#post3206924[
Cruise Forum Thread]

== OpenPlotter HATS

These HATS will work for certain with
https://forum.openmarine.net/showthread.php?tid=868[OpenPlotter HATS]

Moitessier Hat (available): AIS + GNSS + compass + heel + trim MacArthur Hat
(development): UPS (battery) + on/off switch + … Slocum Hat (development):
Analog to digital converter + I2C/1W/GPIO easy connection + …

Another PCB effort I do not have any need for Wifi and will probably
multiplex input signals in hardware instead. I have one USB plug that
acts both as a HID for the keys/buttons and a CDC for serial, aggregating
a number of serial signals as a combined NMEA stream. In this case a small
PCB that will plug into the raspberry and allow you to connect just about
any 40-pin TFT with touch and also accommodate several NMEA inputs as well
as real buttons. This PCB stacked with the Moitessier hat would make a very
capable, almost plug and play, plotter.

== Hat from MCM for Openplotter

Note Well!! This hat is obsolete and not fully supported by OpenPlotter.

https://www.tindie.com/stores/mcm_solutions/[MCM Solutions]
https://www.tindie.com/products/mcm_solutions/openplotter-hat-for-raspberry-pi/

* Power Supply with extra USB(power), UPS and 2200ma battery backup (2hr)
  with sensors.
* GPS (Antenova M10478-M2), IMU (Compass, Gyro, Acceleration), MPU9250 from
  Invensense, Air pressure (LPS25HB from ST)
* Humidity (SHT21 from Sensirion), LDO voltage regulator for GPS and sensors
  for optimal performance, audio connections, digital Class D audio amplifier
  with 3.2 Watt Power (MAX98357A)
* 2-pin 0.1″ header for direct connection of the loudspeaker, speaker
  connection additionally on 6-pin ribbon connector.
* Designed to fit in
  https://www.amazon.com/Raspberry-Pi-Case-Black-fits/dp/B00UW2G1BS[
  OneNineDesign Case] for RPI-RPI3 with the battery]]

== TackTick WiFi

http://phoenixketch.blogspot.com/2019/01/building-marine-navigational-computer.html[
Phoenix's RPI3 and Tacktick] We have a Tacktick wireless network and we
interfaced it into our RPi using a USB RS232 cable from the Tacktick NMEA
interface (T122). Works great. I suppose you could create your own
interface but we had enough fun trail blazing for setting up the earlier
versions of OCPN on the pi and luckily our system came w/the T122.

== Arduino Wifi + SignalK for Nmea0183

https://bitbucket.org/toQDuj/signalk-wifi-nodules/src[Connects to a
"Reciever" RPI + OpenPlotter, another low powered solution for wifi + Nmea0183]

== Lightweight Communication

Draws much less power than the VHF set, though no good for weatherfax. Handy
for ocean passages as well though to keep a Vhf watch drawing little r power.

https://baofengtech.com//product/uv-5r/[BaoFeng UV5R Transmitter], 4 watt UHF / 4 watt
VHF, draws milliamps. Costs about $30-50 USD. Requires Ham License for
transmit. +
http://www.eham.net/reviews/detail/10349[eHam Review] UV5R List (discontinued)
https://www.buytwowayradios.com/baofeng-uv-5r.html[More Details] To
power the basse, use a buck converter to 8vdc or small regulator. +
https://baofengtech.com/product/bf-f8hp/[BaoFeng BFF8HP],
http://www.eham.net/reviews/detail/11882[Review], is the successor. +
http://www.eham.net/reviews/detail/198[Icom T8AReview]
http://www.eham.net/reviews/detail/2350[Yaesu VX-7A Review] These are both
old,  more expensive rn ecent ones available.

You can do a lot with 4 watts, if you have a good antenna and good
installation. My fixed VHF set is usually kept on 1 watt. I've had “weak but
readable” signal reports from 60 miles. I have a decent VHF/UHF Diamond
antenna on a spreader, connected with RG214. A 5 watt Icom VHF/UHF handy
talky hooked up to that does remarkable things over water.

== Weatherfax
Broadband Radar with Chart Overlay

Chart overlay on RPI-2B with Opencpn 4.8 and BR24radar_pi v3.0. The radar
traffic via ethernet wiree to eth0. All NMEA 0183 via wireless lan. MARPA
works fine, the radar window is slow while opening, but also works also
fine. I use Rasbian out of the box and OCPN is locally built.

== Arduino Alternator Regulator

http://arduinoalternatorregulator.blogspot.com/[Arduino Alternator Regulator
Can], Nmea2000, Signal-K

http://www.cruisersforum.com/forums/showthread.php?t=194917[
Next Gen Alternator Thread - Cruisers Forum]

https://www.youtube.com/playlist?list=PLh8BEnfg2z52YcFEMpvMLLWS3f3tVwHHe[
Projects with RPI and Arduino Videos]

== Setting up a GPIO-Button “keyboard” on a Raspberry Pi

https://www.cruisersforum.com/forums/f134/ctrl-m-on-hardwired-button-232008.html#post3101411[
RPI GPIO-Button “keyboard” on Cruiseer's Forum]

http://blog.gegg.us/2017/01/setting-up-a-gpio-button-keyboard-on-a-raspberry-pi/[
Setting up a GPIO-Button “keyboard” on a Raspberry Pi - Original]
