== FAQ

* *How can errors in the manual be reported*

Please use the issues link in the main repository:

https://github.com/Rasbats/opencpn-plugins-manual/issues

* *What is the best way of making images show when using Firefox to open
an .adoc file*

At the top of the document (.adoc) add the attribute ``:imagesdir:
../images/'' This will not appear in the page but controls the location
of the images.

* *Where is the latest build of the OpenCPN Plugins Manual*

Latest build is here:

https://rasbats.github.io/opencpn-plugins-manual/opencpn-plugins-manual/0.1/index.html

* *How can the manual be edited*

[arabic]
. Top right of your pages you will see `Edit this page'. Using this
allows edits of the manual on Github. On the next build of your plugin
the edits will be seen in the manual (after the main manual is updated).
. Using the manual pages in your plugin repository.

* *Are there tools that ``automagically'' converts markdown markup
language (eg. the README.md file in the github repo) to asciidocs ?* Yes
I have made an amateur python script for this. WIP

BTW if you need HTML for a help button you will find it at:
https://github.com/Rasbats/opencpn-plugins-manual/tree/main/docs/radar/0.1
This could be placed in a folder in your data directory and referenced
by the plugin.


